version: "3.8"
services:
  # TYPESENSE
  search_engine:
    image: typesense/typesense:0.24.0
    restart: "always"
    ports:
      - "${PORT}:8108"
    volumes:
      - "search_engine_data:/data"
    environment:
      TYPESENSE_API_KEY: "${API_KEY}"
      TYPESENSE_DATA_DIR: "/data"
      TYPESENSE_ENABLE_CORS: "false"

volumes:
  search_engine_data:
